export const PRESET_LISTS = [
  // ---------------------------
  // BIST listeleri
  // ---------------------------
  {
    id: 'bist30-endeksi-hisseleri',
    title: 'BIST30 Endeksi Hisseleri',
    emoji: '😎',
    iconImage: '/listicon/bist30endeksi.png',
    description: 'BIST30 endeksinde yer alan tam hisse listesi.',
    market: 'bist',
    symbols: [
      'AKBNK.IS',
      'AKSEN.IS',
      'ALARK.IS',
      'ARENA.IS',
      'ASELS.IS',
      'BIMAS.IS',
      'DOHOL.IS',
      'DOAS.IS',
      'EKGYO.IS',
      'ENJSA.IS',
      'ENKAI.IS',
      'EREGL.IS',
      'FROTO.IS',
      'GARAN.IS',
      'KCHOL.IS',
      'KRDMD.IS',
      'KOZAL.IS',
      'MGROS.IS',
      'PETKM.IS',
      'PGSUS.IS',
      'SAHOL.IS',
      'SISE.IS',
      'TAVHL.IS',
      'TCELL.IS',
      'THYAO.IS',
      'TTRAK.IS',
      'TUPRS.IS',
      'VESTL.IS',
      'YKBNK.IS'
    ],
  },
  
  {
    id: 'tly-içindekiler',
    title: 'TLY Fonu Hisseleri',
    emoji: '😎',
    iconImage: '/listicon/tlyicindekiler.png',
    description: 'TLY Fonunda yer aldığı bilinen tüm hisseler.',
    market: 'bist',
    symbols: [
      'TEHOL.IS',
      'TERA.IS',
      'TRHOL.IS',
      'DSTKF.IS',
      'TURSG.IS',
      'SMRVA.IS',
      'HEDEF.IS',
      'PEKGY.IS',
      'GRTHO.IS',
      'ADESE.IS'
    ],
  },

  {
    id: 'altini-yenen-hisseler',
    title: 'Altını Yenen Hisseler',
    emoji: '✨',
    iconImage: '/listicon/bistaltınıyenenler.png',
    description: 'Son yillarda altini geride birakan guclu BIST hisseleri.',
    market: 'bist',
    symbols: ['ASELS.IS', 'TUPRS.IS', 'MGROS.IS', 'BIMAS.IS', 'SISE.IS'],
  },
  {
    id: 'enerji-hisseleri',
    title: 'Enerji Hisseleri',
    emoji: '⚡',
    iconImage: '/listicon/bistenerjihisseleri.png',
    description: 'Turkiye enerji ve petrokimya sirketleri.',
    market: 'bist',
    symbols: ['TUPRS.IS', 'AKSEN.IS', 'ENJSA.IS', 'PETKM.IS', 'ZOREN.IS'],
  },
  {
    id: 'bankacilik-bist',
    title: 'BIST Bankacılık Hisseleri',
    emoji: '🏦',
    iconImage: '/listicon/bistbankacılık.png',
    description: 'Turkiye nin buyuk bankalari.',
    market: 'bist',
    symbols: [
      'AKBNK.IS',
      'GARAN.IS',
      'YKBNK.IS',
      'ISCTR.IS',
      'HALKB.IS',
      'VAKBN.IS',
      'TSKB.IS',
    ],
  },
  {
    id: 'holding-hisseleri',
    title: 'Holding ve Yatırım Şirketleri',
    emoji: '🏢',
    iconImage: '/listicon/placeholder.png',
    description: 'Turkiye nin onde gelen holding ve yatirim sirketleri.',
    market: 'bist',
    symbols: ['KCHOL.IS', 'SAHOL.IS', 'DOHOL.IS', 'AGHOL.IS', 'GSDHO.IS'],
  },
  {
    id: 'perakende-hisseleri',
    title: 'Perakende ve Market Zincirleri',
    emoji: '🛒',
    iconImage: '/listicon/placeholder.png',
    description: 'Perakende ve magazacilik sektorunun one cikanlari.',
    market: 'bist',
    symbols: ['BIMAS.IS', 'MGROS.IS', 'SOKM.IS', 'MAVI.IS'],
  },
  {
    id: 'savunma-sanayi',
    title: 'Savunma Sanayi Hisseleri',
    emoji: '🛡️',
    iconImage: '/listicon/placeholder.png',
    description: 'Savunma sanayinde faaliyet gosteren sirketler.',
    market: 'bist',
    symbols: ['ASELS.IS', 'KONTR.IS', 'OTKAR.IS', 'MKE.IS'],
  },
  {
    id: 'havacilik-turizm',
    title: 'Havacılık ve Turizm',
    emoji: '✈️',
    iconImage: '/listicon/placeholder.png',
    description: 'Havayolu ve turizm sektorundeki liderler.',
    market: 'bist',
    symbols: ['THYAO.IS', 'PGSUS.IS', 'TAVHL.IS', 'DOCO.IS'],
  },

  // Ek BIST listeleri (daha detayli ve tematik)
  {
    id: 'bist100-secilmis-hisseler',
    title: 'BIST100 Seçilmiş Hisseler',
    emoji: '📈',
    iconImage: '/listicon/placeholder.png',
    description: 'BIST100 endeksinden likit ve takip edilen secili hisseler.',
    market: 'bist',
    symbols: [
      'AKBNK.IS',
      'ASELS.IS',
      'BIMAS.IS',
      'ENJSA.IS',
      'EREGL.IS',
      'FROTO.IS',
      'GARAN.IS',
      'ISCTR.IS',
      'KCHOL.IS',
      'KOZAL.IS',
      'MGROS.IS',
      'PETKM.IS',
      'SAHOL.IS',
      'SISE.IS',
      'TCELL.IS',
      'THYAO.IS',
      'TOASO.IS',
      'TUPRS.IS',
      'VESTL.IS',
      'YKBNK.IS',
    ],
  },
  {
    id: 'bist-temettu-hisseleri',
    title: 'BIST Temettü Ödeme Alışkanlığı Yüksek Hisseler',
    emoji: '💰',
    iconImage: '/listicon/placeholder.png',
    description: 'Duzgun temettu gecmisiyle on plana cikan secili BIST sirketleri.',
    market: 'bist',
    symbols: [
      'AKBNK.IS',
      'ALARK.IS',
      'EREGL.IS',
      'FROTO.IS',
      'ISDMR.IS',
      'TOASO.IS',
      'TTRAK.IS',
      'SISE.IS',
      'TCELL.IS',
      'ENJSA.IS',
    ],
  },
  {
    id: 'bist-katilim-endeksi-secilmis',
    title: 'BIST Katılım Endeksi Seçili Hisseler',
    emoji: '☪️',
    iconImage: '/listicon/placeholder.png',
    description:
      'Katilim endekslerinde yer alan, faizsiz finans ilkelerine uygun secili hisseler.',
    market: 'bist',
    symbols: [
      'ALBRK.IS',
      'AKSA.IS',
      'ALKIM.IS',
      'ASELS.IS',
      'KARSN.IS',
      'KONTR.IS',
      'OTKAR.IS',
      'PETKM.IS',
      'TTRAK.IS',
    ],
  },
  {
    id: 'bist-sanayi-ihracatcilar',
    title: 'BIST Sanayi İhracatçıları',
    emoji: '🏭',
    iconImage: '/listicon/placeholder.png',
    description: 'Ciroda ihracat payi yuksek sanayi sirketlerinden secili ornekler.',
    market: 'bist',
    symbols: [
      'EREGL.IS',
      'ISDMR.IS',
      'FROTO.IS',
      'TOASO.IS',
      'TTRAK.IS',
      'ARCLK.IS',
      'VESTL.IS',
      'VESBE.IS',
      'KRDMD.IS',
    ],
  },
  {
    id: 'bist-teknoloji-yazilim',
    title: 'BIST Teknoloji ve Yazılım',
    emoji: '💻',
    iconImage: '/listicon/placeholder.png',
    description: 'Teknoloji, yazilim ve telekom odakli BIST sirketleri.',
    market: 'bist',
    symbols: [
      'LOGO.IS',
      'ARENA.IS',
      'DESPC.IS',
      'NETAS.IS',
      'KAREL.IS',
      'TCELL.IS',
      'ARDYZ.IS',
    ],
  },
  {
    id: 'bist-gyo',
    title: 'BIST GYO Gayrimenkul Yatırım Ortaklıkları',
    emoji: '🏙️',
    iconImage: '/listicon/placeholder.png',
    description: 'Borsa Istanbul da islem goren secili GYO sirketleri.',
    market: 'bist',
    symbols: [
      'EKGYO.IS',
      'ALGYO.IS',
      'SNGYO.IS',
      'TRGYO.IS',
      'TSGYO.IS',
      'NUGYO.IS',
      'KLGYO.IS',
    ],
  },
  {
    id: 'bist-saglik-ilac',
    title: 'BIST Sağlık ve İlaç',
    emoji: '🩺',
    iconImage: '/listicon/placeholder.png',
    description: 'Saglik, ilac ve ecza alaninda faaliyet gosteren sirketler.',
    market: 'bist',
    symbols: ['ECILC.IS', 'DEVA.IS', 'MPARK.IS', 'SELEC.IS'],
  },
  {
    id: 'bist-tuketim-gida-icecek',
    title: 'BIST Tüketim, Gıda ve İçecek',
    emoji: '🍽️',
    iconImage: '/listicon/placeholder.png',
    description: 'Tuketim, gida ve icecek sektorundeki onde gelen sirketler.',
    market: 'bist',
    symbols: ['BIMAS.IS', 'MGROS.IS', 'ULKER.IS', 'CCOLA.IS', 'TBORG.IS'],
  },
  {
    id: 'bist-enerji-yenilenebilir',
    title: 'BIST Yenilenebilir Enerji',
    emoji: '🌱',
    iconImage: '/listicon/placeholder.png',
    description: 'Yenilenebilir enerji ve elektrik uretim odakli sirketler.',
    market: 'bist',
    symbols: [
      'AKSEN.IS',
      'AYDEM.IS',
      'YEOTK.IS',
      'GWIND.IS',
      'MAGEN.IS',
      'GESAN.IS',
      'ORGE.IS',
      'SAYAS.IS',
      'TATEN.IS',
    ],
  },
  {
    id: 'bist-otomotiv-tedarikciler',
    title: 'BIST Otomotiv ve Tedarikçiler',
    emoji: '🚗',
    iconImage: '/listicon/placeholder.png',
    description: 'Otomotiv ureticileri ve tedarikci agindaki sirketler.',
    market: 'bist',
    symbols: [
      'FROTO.IS',
      'TOASO.IS',
      'DOAS.IS',
      'KARSN.IS',
      'ASUZU.IS',
      'TMSN.IS',
      'OTKAR.IS',
    ],
  },

  // ---------------------------
  // ABD borsalari
  // ---------------------------
  {
    id: 'sp500-mega-cap',
    title: 'S&P 500 Mega-Cap',
    emoji: '🇺🇸',
    iconImage: '/listicon/placeholder.png',
    description: 'ABD nin en buyuk piyasa degerine sahip sirketleri.',
    market: 'us',
    symbols: ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'NVDA', 'BRK.B', 'TSLA'],
  },
  {
    id: 'nasdaq-teknoloji-devleri',
    title: 'NASDAQ Teknoloji Devleri',
    emoji: '💻',
    iconImage: '/listicon/placeholder.png',
    description: 'Teknolojide dunyanin en buyuk sirketleri.',
    market: 'us',
    symbols: ['AAPL', 'MSFT', 'NVDA', 'GOOG', 'ADBE', 'AVGO', 'AMD', 'INTC'],
  },

  // Ek ABD / tematik listeler
  {
    id: 'us-yari-iletken-devleri',
    title: 'ABD ve Global Yarı İletken Devleri',
    emoji: '🧠',
    iconImage: '/listicon/placeholder.png',
    description: 'Cip ve yari iletken sektorunun onde gelen sirketleri.',
    market: 'us',
    symbols: [
      'NVDA',
      'AVGO',
      'AMD',
      'QCOM',
      'MU',
      'TXN',
      'MRVL',
      'ASML',
      'TSM',
      'ADI',
    ],
  },
  {
    id: 'us-dividend-aristocrats-secilmis',
    title: 'ABD Dividend Aristocrats Secili',
    emoji: '🏛️',
    iconImage: '/listicon/placeholder.png',
    description:
      'Uzun yillar boyunca temettusunu artiran ABD sirketlerinden secili ornekler.',
    market: 'us',
    symbols: ['KO', 'PG', 'JNJ', 'MCD', 'PEP', 'EMR', 'DOV', 'GPC'],
  },
  {
    id: 'us-buyume-teknoloji',
    title: 'ABD Büyüme Odaklı Teknoloji Hisseleri',
    emoji: '🚀',
    iconImage: '/listicon/placeholder.png',
    description:
      'Yuksek buyume potansiyeliyle one cikan teknoloji ve yazilim sirketleri.',
    market: 'us',
    symbols: ['TSLA', 'SNOW', 'CRWD', 'NET', 'ABNB', 'SHOP', 'DDOG', 'PLTR'],
  },

  // ---------------------------
  // Fon ve ETF listeleri
  // ---------------------------
  {
    id: 'genis-piyasa-etf',
    title: 'Geniş Piyasa ETF Fonları',
    emoji: '📊',
    iconImage: '/listicon/placeholder.png',
    description: 'ABD ve dunya genelini kapsayan genis endeks ETF leri.',
    market: 'funds',
    symbols: ['VOO', 'SPY', 'IVV', 'VTI', 'SCHB'],
  },
  {
    id: 'altin-gumus-etf',
    title: 'Altın ve Gümüş ETF Fonları',
    emoji: '🥇',
    iconImage: '/listicon/placeholder.png',
    description: 'Altin ve degerli metal ETF leri.',
    market: 'funds',
    symbols: ['GLD', 'IAU', 'SLV', 'GDX', 'GDXJ'],
  },
  {
    id: 'us-teknoloji-etfleri',
    title: 'ABD Teknoloji ETF leri',
    emoji: '🛰️',
    iconImage: '/listicon/placeholder.png',
    description: 'ABD teknoloji ve buyuk cap growth odakli ETF ler.',
    market: 'funds',
    symbols: ['XLK', 'VGT', 'QQQ', 'IGM', 'SMH', 'SOXX'],
  },
  {
    id: 'yenilenebilir-enerji-etfleri',
    title: 'Yenilenebilir Enerji ETF leri',
    emoji: '🌱',
    iconImage: '/listicon/placeholder.png',
    description:
      'Temiz enerji, solar ve yesil donusum temali ETF portfoyleri.',
    market: 'funds',
    symbols: ['ICLN', 'TAN', 'QCLN', 'PBW'],
  },
  {
    id: 'dunya-genis-endeks-etf',
    title: 'Dünya Geniş Endeks ETF leri',
    emoji: '🌎',
    iconImage: '/listicon/placeholder.png',
    description:
      'Gelismis ve gelisen ulkeleri kapsayan genis dunya endeks ETF leri.',
    market: 'funds',
    symbols: ['URTH', 'ACWI', 'VT', 'VEU', 'VXUS'],
  },

  // ---------------------------
  // Global / Other
  // ---------------------------
  {
    id: 'avrupa-mavi-cipler',
    title: 'Avrupa Mavi Çip Hisseleri',
    emoji: '🇪🇺',
    iconImage: '/listicon/placeholder.png',
    description: 'Avrupa nin en buyuk sirketleri.',
    market: 'other',
    symbols: ['NESN.SW', 'SIE.DE', 'AIR.PA', 'RMS.PA', 'NOVN.SW', 'VOW3.DE'],
  },
  {
    id: 'global-enerji-devleri',
    title: 'Global Enerji Devleri',
    emoji: '🌍',
    iconImage: '/listicon/placeholder.png',
    description: 'Dunya genelinde enerji devleri.',
    market: 'other',
    symbols: ['XOM', 'CVX', 'BP', 'SHEL', 'TTE', 'EQNR'],
  },

  // Kriptoyu other altina aldik
  {
    id: 'kripto-en-buyukler',
    title: 'Kripto Para Piyasa Değeri En Büyükler',
    emoji: '🧩',
    iconImage: '/listicon/placeholder.png',
    description:
      'Piyasa degerine gore en buyuk secili kripto paralar USD bazinda.',
    market: 'other',
    symbols: ['BTC-USD', 'ETH-USD', 'SOL-USD', 'BNB-USD', 'XRP-USD'],
  },
];
